"""Playtest — Godot 4 headless runner + checkpoint helper + report generator.

Drives `godot --headless` against a project, captures periodic screenshots
and stdout/stderr, then collates everything into a markdown bug-surface
report the agent can read directly.

Subcommands
-----------
headless    Run `godot --headless --path PROJECT --main-scene SCENE` for
            N seconds, capturing screenshots every M seconds and tee'ing
            stdout/stderr to a log file. Exits with Godot's exit code.

checkpoint  Emit a PlaytestCheckpoint.gd autoload helper that the user
            drops into their project. It exposes `screenshot(name)` and
            `mark(event)` methods callable from any scene script to
            capture state at known game points.

report      Walk a run directory (logs + screenshots) and emit a
            markdown report summarizing: exit code, runtime, error/
            warning lines from the log, screenshot timeline, FPS stats
            if printed.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path


# ---------------------------------------------------------------------------
# Godot binary resolution
# ---------------------------------------------------------------------------

def _godot_binary() -> str:
    """Pick a Godot 4 binary. Env GODOT_BIN wins; else first found in PATH."""
    explicit = os.environ.get("GODOT_BIN", "").strip()
    if explicit:
        return explicit
    for candidate in ("godot", "godot4", "Godot_v4.exe", "godot.exe"):
        path = shutil.which(candidate)
        if path:
            return path
    return "godot"  # let subprocess raise if not found


# ---------------------------------------------------------------------------
# Synthesized runner script — copied into the project temporarily so Godot
# can load it as the main script for the headless run.
# ---------------------------------------------------------------------------

RUNNER_GD = '''extends SceneTree
# Auto-generated by godogen/playtest. Drives a headless run that loads
# {main_scene}, plays for {duration_s} seconds, captures a screenshot
# every {interval_s} seconds, then quits.

const MAIN_SCENE := "{main_scene}"
const DURATION_S := {duration_s}
const INTERVAL_S := {interval_s}
const OUTPUT_DIR := "{output_dir_godot}"

var _elapsed: float = 0.0
var _next_shot: float = 0.0
var _shot_idx: int = 0

func _init() -> void:
    print("[playtest] starting run, main_scene=%s, duration=%ss, interval=%ss" % [MAIN_SCENE, DURATION_S, INTERVAL_S])
    var dir := DirAccess.open("res://")
    if dir == null:
        print("[playtest] ERROR: cannot open res://")
        quit(2)
        return
    dir.make_dir_recursive(OUTPUT_DIR)
    var scene := load(MAIN_SCENE)
    if scene == null:
        print("[playtest] ERROR: scene %s did not load" % MAIN_SCENE)
        quit(2)
        return
    var inst = scene.instantiate()
    root.add_child(inst)
    print("[playtest] scene instanced; entering simulation loop")
    process_frame.connect(_on_frame)

func _on_frame() -> void:
    var dt := get_root().get_process_delta_time()
    _elapsed += dt
    if _elapsed >= _next_shot:
        _capture(_shot_idx)
        _shot_idx += 1
        _next_shot += INTERVAL_S
    if _elapsed >= DURATION_S:
        print("[playtest] reached duration limit, took %d shots" % _shot_idx)
        quit(0)

func _capture(idx: int) -> void:
    var img := get_root().get_viewport().get_texture().get_image()
    if img == null:
        print("[playtest] WARN: viewport image null at shot %d" % idx)
        return
    var path := "%s/shot_%03d.png" % [OUTPUT_DIR, idx]
    var err := img.save_png(path)
    if err == OK:
        print("[playtest] shot %d -> %s @ t=%.2fs" % [idx, path, _elapsed])
    else:
        print("[playtest] WARN: save_png failed for %s (err=%d)" % [path, err])
'''


# ---------------------------------------------------------------------------
# Checkpoint autoload — for users to add to their project
# ---------------------------------------------------------------------------

CHECKPOINT_GD = '''extends Node
# PlaytestCheckpoint — drop this into Project Settings > Autoload as
# "PlaytestCheckpoint" so it's reachable from any scene. Then call:
#     PlaytestCheckpoint.screenshot("level_1_loaded")
#     PlaytestCheckpoint.mark("boss_spawned", {"hp": boss.hp})
#
# Both methods are no-ops unless OS.has_environment("PLAYTEST_ACTIVE").
# That lets you leave the calls in production code without runtime cost
# beyond the env-var check.

const OUTPUT_DIR := "user://playtest_checkpoints/"

func _ready() -> void:
    if not OS.has_environment("PLAYTEST_ACTIVE"):
        return
    DirAccess.make_dir_recursive_absolute(OUTPUT_DIR)
    print("[playtest_checkpoint] enabled, output -> %s" % OUTPUT_DIR)

func screenshot(name: String) -> void:
    if not OS.has_environment("PLAYTEST_ACTIVE"):
        return
    var img := get_viewport().get_texture().get_image()
    if img == null:
        print("[playtest_checkpoint] WARN: viewport image null for %s" % name)
        return
    var ts := Time.get_unix_time_from_system()
    var path := "%s%d_%s.png" % [OUTPUT_DIR, ts, _sanitize(name)]
    var err := img.save_png(path)
    if err == OK:
        print("[playtest_checkpoint] screenshot: %s" % path)
    else:
        print("[playtest_checkpoint] WARN: save_png failed for %s" % path)

func mark(event: String, data: Dictionary = {}) -> void:
    if not OS.has_environment("PLAYTEST_ACTIVE"):
        return
    var ts := Time.get_unix_time_from_system()
    var line := "%d  %s  %s" % [ts, event, JSON.stringify(data)]
    print("[playtest_checkpoint] %s" % line)
    var f := FileAccess.open(OUTPUT_DIR + "events.log", FileAccess.READ_WRITE)
    if f == null:
        f = FileAccess.open(OUTPUT_DIR + "events.log", FileAccess.WRITE)
    if f != null:
        f.seek_end()
        f.store_line(line)
        f.close()

func _sanitize(s: String) -> String:
    var out := ""
    for c in s:
        if c.is_valid_identifier() or c == "_":
            out += c
        else:
            out += "_"
    return out
'''


# ---------------------------------------------------------------------------
# headless subcommand
# ---------------------------------------------------------------------------

def cmd_headless(args):
    project_path = Path(args.project).resolve()
    if not (project_path / "project.godot").exists():
        raise SystemExit(f"--project does not look like a Godot project (no project.godot): {project_path}")

    run_id = args.run_id or f"run_{int(time.time())}"
    output_root = Path(args.output_dir).resolve() / run_id
    output_root.mkdir(parents=True, exist_ok=True)
    log_path = output_root / "stdout.log"
    screenshots_subdir = output_root / "screenshots"
    # In Godot res:// terms, screenshots will be written under the project
    # tree because we don't have user:// configured for our temp runner.
    # Use a project-relative path the runner can DirAccess.
    rel_shots = f"playtest_screenshots/{run_id}"
    abs_shots_in_project = project_path / rel_shots
    abs_shots_in_project.mkdir(parents=True, exist_ok=True)

    # Write the temp runner script into the project (we'll delete after).
    runner_path = project_path / "_playtest_runner.gd"
    runner_path.write_text(
        RUNNER_GD.format(
            main_scene=args.main_scene,
            duration_s=args.duration,
            interval_s=args.interval,
            output_dir_godot=rel_shots,
        ),
        encoding="utf-8",
    )

    godot = _godot_binary()
    cmd = [
        godot, "--headless",
        "--path", str(project_path),
        "--script", "res://_playtest_runner.gd",
    ]
    print(f"[playtest.headless] launching: {' '.join(cmd)}", file=sys.stderr)
    print(f"[playtest.headless] log -> {log_path}", file=sys.stderr)

    started = time.time()
    try:
        with open(log_path, "wb") as logf:
            proc = subprocess.Popen(
                cmd, stdout=logf, stderr=subprocess.STDOUT,
                env={**os.environ, "PLAYTEST_ACTIVE": "1"},
            )
            try:
                exit_code = proc.wait(timeout=args.duration + args.timeout_grace)
            except subprocess.TimeoutExpired:
                proc.kill()
                exit_code = -1
    finally:
        try:
            runner_path.unlink()
        except OSError:
            pass

    elapsed = time.time() - started

    # Move the project-side screenshots into our output_root for portability.
    moved: list[str] = []
    if abs_shots_in_project.exists():
        screenshots_subdir.mkdir(parents=True, exist_ok=True)
        for p in sorted(abs_shots_in_project.glob("shot_*.png")):
            dest = screenshots_subdir / p.name
            shutil.move(str(p), str(dest))
            moved.append(str(dest))
        try:
            abs_shots_in_project.rmdir()
            (project_path / "playtest_screenshots").rmdir()
        except OSError:
            pass

    print(json.dumps({
        "ok": exit_code == 0,
        "subcommand": "headless",
        "run_id": run_id,
        "exit_code": exit_code,
        "elapsed_s": round(elapsed, 2),
        "log": str(log_path),
        "screenshots_dir": str(screenshots_subdir),
        "screenshot_count": len(moved),
        "godot_binary": godot,
    }, indent=2))


# ---------------------------------------------------------------------------
# checkpoint subcommand
# ---------------------------------------------------------------------------

def cmd_checkpoint(args):
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(CHECKPOINT_GD, encoding="utf-8")
    print(json.dumps({
        "ok": True, "subcommand": "checkpoint",
        "script": str(out_path),
        "usage": (
            "1. Save this script in your Godot project (e.g. res://addons/playtest/PlaytestCheckpoint.gd). "
            "2. Project Settings -> Autoload -> add as 'PlaytestCheckpoint'. "
            "3. Call PlaytestCheckpoint.screenshot('event_name') or .mark('event', {...}) from scene scripts. "
            "4. Set PLAYTEST_ACTIVE=1 env var when launching the game to enable capture; unset for production."
        ),
    }, indent=2))


# ---------------------------------------------------------------------------
# report subcommand — collate a run dir into markdown
# ---------------------------------------------------------------------------

# Match common error/warning patterns in Godot logs.
ERROR_PATTERNS = [
    re.compile(r"^ERROR:", re.IGNORECASE),
    re.compile(r"^SCRIPT ERROR:", re.IGNORECASE),
    re.compile(r"Traceback \(", re.IGNORECASE),
    re.compile(r"failed to", re.IGNORECASE),
    re.compile(r"cannot ", re.IGNORECASE),
]

WARNING_PATTERNS = [
    re.compile(r"^WARNING:", re.IGNORECASE),
    re.compile(r"^WARN:", re.IGNORECASE),
    re.compile(r"deprecated", re.IGNORECASE),
]


def _classify_log_line(line: str) -> str:
    for pat in ERROR_PATTERNS:
        if pat.search(line):
            return "error"
    for pat in WARNING_PATTERNS:
        if pat.search(line):
            return "warning"
    if "[playtest]" in line or "[playtest_checkpoint]" in line:
        return "playtest"
    return "info"


def cmd_report(args):
    run_dir = Path(args.run_dir).resolve()
    if not run_dir.exists():
        raise SystemExit(f"Run directory not found: {run_dir}")

    log_path = run_dir / "stdout.log"
    screenshots_dir = run_dir / "screenshots"

    # Parse log
    errors: list[str] = []
    warnings: list[str] = []
    playtest_events: list[str] = []
    info_lines: list[str] = []
    if log_path.exists():
        for line in log_path.read_text(encoding="utf-8", errors="replace").splitlines():
            cls = _classify_log_line(line)
            if cls == "error":
                errors.append(line)
            elif cls == "warning":
                warnings.append(line)
            elif cls == "playtest":
                playtest_events.append(line)
            else:
                info_lines.append(line)

    shots: list[Path] = []
    if screenshots_dir.exists():
        shots = sorted(screenshots_dir.glob("shot_*.png"))

    md: list[str] = []
    md.append(f"# Playtest report — {run_dir.name}")
    md.append("")
    md.append("## Summary")
    md.append("")
    md.append(f"- **Errors**: {len(errors)}")
    md.append(f"- **Warnings**: {len(warnings)}")
    md.append(f"- **Playtest events**: {len(playtest_events)}")
    md.append(f"- **Screenshots**: {len(shots)}")
    md.append(f"- **Log lines (total)**: {len(errors) + len(warnings) + len(playtest_events) + len(info_lines)}")
    md.append("")
    if errors:
        md.append("## Errors")
        md.append("")
        for e in errors:
            md.append(f"- `{e.strip()}`")
        md.append("")
    if warnings:
        md.append("## Warnings")
        md.append("")
        for w in warnings:
            md.append(f"- `{w.strip()}`")
        md.append("")
    if playtest_events:
        md.append("## Playtest events")
        md.append("")
        for p in playtest_events:
            md.append(f"- `{p.strip()}`")
        md.append("")
    if shots:
        md.append("## Screenshot timeline")
        md.append("")
        for shot in shots:
            rel = shot.relative_to(run_dir).as_posix()
            md.append(f"- ![{shot.name}]({rel})")
        md.append("")
    if not errors and not warnings:
        md.append("## Verdict")
        md.append("")
        md.append("Clean run — no errors or warnings detected in the log.")
        md.append("")
    elif errors:
        md.append("## Verdict")
        md.append("")
        md.append(f"**FAIL** — {len(errors)} error(s) detected. Investigate the entries above before shipping.")
        md.append("")
    else:
        md.append("## Verdict")
        md.append("")
        md.append(f"PASS with {len(warnings)} warning(s). Review warnings; not blocking.")
        md.append("")

    out_path = Path(args.output) if args.output else (run_dir / "report.md")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(md), encoding="utf-8")

    verdict = "fail" if errors else ("warn" if warnings else "pass")
    print(json.dumps({
        "ok": True, "subcommand": "report",
        "report": str(out_path),
        "verdict": verdict,
        "errors": len(errors), "warnings": len(warnings),
        "playtest_events": len(playtest_events),
        "screenshots": len(shots),
    }, indent=2))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="playtest: Godot headless + checkpoint + report")
    sub = parser.add_subparsers(required=True, dest="cmd")

    p = sub.add_parser("headless", help="Run Godot headless, capture screenshots + log")
    p.add_argument("--project", required=True, help="Path to Godot project (containing project.godot)")
    p.add_argument("--main-scene", required=True, help="res:// path to scene to instantiate")
    p.add_argument("--duration", type=int, default=20, help="Run duration in seconds")
    p.add_argument("--interval", type=int, default=5, help="Screenshot interval in seconds")
    p.add_argument("--output-dir", default="playtest_runs", help="Where to write the run dir")
    p.add_argument("--run-id", default="", help="Run identifier (default: timestamp)")
    p.add_argument("--timeout-grace", type=int, default=10,
                   help="Extra seconds before killing the process past --duration")
    p.set_defaults(func=cmd_headless)

    p = sub.add_parser("checkpoint", help="Emit PlaytestCheckpoint.gd autoload helper")
    p.add_argument("-o", "--output", required=True, help="Output .gd file path")
    p.set_defaults(func=cmd_checkpoint)

    p = sub.add_parser("report", help="Collate a run directory into a markdown report")
    p.add_argument("--run-dir", required=True, help="Run directory (from headless)")
    p.add_argument("-o", "--output", default="", help="Report path (default: <run_dir>/report.md)")
    p.set_defaults(func=cmd_report)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
