"""Save System — Godot 4 save-system scaffold generator.

Emits four pieces, individually or together:
  save_data.gd       Typed Resource model with versioned fields + migrate_from().
  save_manager.gd    Autoload singleton: slots, atomic writes, dirty flag.
  autosave.gd        Timer-driven autosave (skips writes when not dirty).
  thumbnail.gd       Viewport-capture helper for slot previews.

Subcommands
-----------
model      Emit save_data.gd from a named preset.
manager    Emit save_manager.gd.
autosave   Emit autosave.gd.
thumbnail  Emit thumbnail.gd.
all        Emit all four (one-shot project scaffold).
list       List available presets and their field sets.

Pure text — no ComfyUI / Tripo3D / etc.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Save-data presets — (field_name, gdscript_type, default_literal, comment)
# ---------------------------------------------------------------------------

PRESETS: dict[str, list[tuple[str, str, str, str]]] = {
    "platformer": [
        ("level_id",          "String",        '""',  "Current level scene id"),
        ("checkpoint_id",     "String",        '""',  "Last checkpoint touched"),
        ("lives",             "int",           "3",   "Remaining lives"),
        ("coins",             "int",           "0",   "Lifetime coin count"),
        ("unlocked_levels",   "Array[String]", "[]",  "All level ids the player has reached"),
        ("power_ups",         "Dictionary",    "{}",  "Held power-ups (id -> count)"),
        ("play_time_seconds", "float",         "0.0", "Total wall-clock play time"),
    ],
    "topdown": [
        ("scene_path",        "String",        '""',  "Current scene .tscn path"),
        ("player_position",   "Vector2",       "Vector2.ZERO", "World-space spawn point on load"),
        ("player_health",     "int",           "100", "Current HP"),
        ("inventory",         "Dictionary",    "{}",  "Item id -> count"),
        ("quest_flags",       "Dictionary",    "{}",  "Quest id -> state string"),
        ("unlocked_areas",    "Array[String]", "[]",  "Area ids the player can fast-travel to"),
        ("play_time_seconds", "float",         "0.0", "Total wall-clock play time"),
    ],
    "rpg": [
        ("scene_path",          "String",        '""',  "Current scene .tscn path"),
        ("player_position",     "Vector2",       "Vector2.ZERO", "World-space spawn point"),
        ("party_members",       "Array",         "[]",  "Array of member dicts (id, hp, mp, xp, level)"),
        ("inventory",           "Dictionary",    "{}",  "Item id -> count"),
        ("gold",                "int",           "0",   "Currency"),
        ("quest_log",           "Array",         "[]",  "Active + completed quest dicts"),
        ("world_flags",         "Dictionary",    "{}",  "Global narrative flags"),
        ("relationship_levels", "Dictionary",    "{}",  "NPC id -> int relationship score"),
        ("play_time_seconds",   "float",         "0.0", "Total wall-clock play time"),
    ],
    "puzzle": [
        ("current_puzzle_id", "String",        '""',  "Last puzzle the player was on"),
        ("solved_puzzles",    "Array[String]", "[]",  "Puzzle ids the player has solved"),
        ("hint_tokens",       "int",           "3",   "Remaining hint tokens"),
        ("total_moves",       "int",           "0",   "Lifetime moves made"),
        ("best_times",        "Dictionary",    "{}",  "Puzzle id -> best float seconds"),
    ],
    "racing": [
        ("unlocked_tracks",       "Array[String]", "[]",  "Track ids the player can race"),
        ("track_records",         "Dictionary",    "{}",  "Track id -> best lap float seconds"),
        ("cash",                  "int",           "0",   "Cash for buying vehicles"),
        ("owned_vehicles",        "Array[String]", "[]",  "Vehicle ids the player owns"),
        ("current_vehicle_id",    "String",        '""',  "Currently selected vehicle"),
        ("total_distance_meters", "float",         "0.0", "Lifetime distance driven"),
    ],
    "minimal": [
        ("play_time_seconds", "float",      "0.0", "Total wall-clock play time"),
        ("data",              "Dictionary", "{}",  "Catch-all (untyped; for prototypes)"),
    ],
}


# ---------------------------------------------------------------------------
# save_data.gd emission
# ---------------------------------------------------------------------------

def _emit_save_data(preset: str) -> str:
    if preset not in PRESETS:
        raise SystemExit(f"Unknown preset {preset!r}. Available: {', '.join(PRESETS)}")
    fields = PRESETS[preset]

    lines: list[str] = []
    lines.append("## Auto-generated by save-system skill (preset: {0}).".format(preset))
    lines.append("## Bump VERSION and add a `migrate_from` branch when you change fields.")
    lines.append("class_name SaveData")
    lines.append("extends Resource")
    lines.append("")
    lines.append("const VERSION := 1")
    lines.append("")
    lines.append("@export var version: int = VERSION")
    for name, gd_type, default, comment in fields:
        lines.append(f"## {comment}")
        lines.append(f"@export var {name}: {gd_type} = {default}")
    lines.append("")
    lines.append("")
    lines.append("## Returns a one-line summary used by the slot picker UI.")
    lines.append("func summary() -> String:")
    if preset == "platformer":
        lines.append("    return \"%s · %d coins · %d lives\" % [level_id, coins, lives]")
    elif preset == "topdown":
        lines.append("    return \"%s · HP %d\" % [scene_path.get_file().get_basename(), player_health]")
    elif preset == "rpg":
        lines.append("    return \"%s · %d gold · party %d\" % [scene_path.get_file().get_basename(), gold, party_members.size()]")
    elif preset == "puzzle":
        lines.append("    return \"%d solved · %d hints\" % [solved_puzzles.size(), hint_tokens]")
    elif preset == "racing":
        lines.append("    return \"%d tracks · $%d\" % [unlocked_tracks.size(), cash]")
    else:
        lines.append("    return \"v%d\" % version")
    lines.append("")
    lines.append("")
    lines.append("## Walks an old Dictionary representation up to the current schema.")
    lines.append("## When you bump VERSION, ADD a branch here; never delete an old one.")
    lines.append("static func migrate_from(old: Dictionary) -> SaveData:")
    lines.append("    var data := SaveData.new()")
    lines.append("    var old_version: int = int(old.get(\"version\", 1))")
    lines.append("    # Example migration scaffold — replace with real branches as you bump VERSION:")
    lines.append("    # if old_version == 1:")
    lines.append("    #     old[\"new_field\"] = default_value")
    lines.append("    #     old_version = 2")
    lines.append("    if old_version != VERSION:")
    lines.append("        push_warning(\"SaveData.migrate_from: no migration branch for v%d -> v%d. Defaults will be used for missing fields.\" % [old_version, VERSION])")
    lines.append("    for key in old:")
    lines.append("        if data.get(key) != null or key in data:")
    lines.append("            data.set(key, old[key])")
    lines.append("    data.version = VERSION")
    lines.append("    return data")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# save_manager.gd emission
# ---------------------------------------------------------------------------

MANAGER_GD = '''## Auto-generated by save-system skill. Register as Autoload `SaveManager`.
## Atomic writes via .tmp + rename. Multi-slot. Cached in-memory.
extends Node

const SAVE_DIR := "user://saves/"
const SLOT_PREFIX := "slot_"
const SAVE_EXT := ".tres"
const TMP_EXT := ".tmp"

signal save_completed(slot: int, success: bool)
signal load_completed(slot: int, success: bool, data: Resource)

var _dirty: bool = false
var _cache: Dictionary = {}  # slot:int -> SaveData


func _ready() -> void:
    DirAccess.make_dir_recursive_absolute(SAVE_DIR)


# --- Dirty flag ------------------------------------------------------------

func mark_dirty() -> void:
    _dirty = true

func is_dirty() -> bool:
    return _dirty

func clear_dirty() -> void:
    _dirty = false


# --- Paths ----------------------------------------------------------------

func slot_path(slot: int) -> String:
    return "%s%s%d%s" % [SAVE_DIR, SLOT_PREFIX, slot, SAVE_EXT]

func slot_thumb_path(slot: int) -> String:
    return "%s%s%d.png" % [SAVE_DIR, SLOT_PREFIX, slot]


# --- Slot enumeration -----------------------------------------------------

func list_slots() -> Array:
    var rows: Array = []
    var dir := DirAccess.open(SAVE_DIR)
    if dir == null:
        return rows
    dir.list_dir_begin()
    var name := dir.get_next()
    var slots_seen: Dictionary = {}
    while name != "":
        if name.begins_with(SLOT_PREFIX) and name.ends_with(SAVE_EXT):
            var slot_str := name.substr(SLOT_PREFIX.length(), name.length() - SLOT_PREFIX.length() - SAVE_EXT.length())
            if slot_str.is_valid_int():
                slots_seen[int(slot_str)] = true
        name = dir.get_next()
    dir.list_dir_end()
    for slot in slots_seen.keys():
        var path := slot_path(slot)
        var modified := FileAccess.get_modified_time(path)
        var summary := ""
        var data: SaveData = _cache.get(slot)
        if data == null:
            data = _peek_summary(slot)
        if data != null:
            summary = data.summary()
        rows.append({
            "slot": slot,
            "exists": true,
            "modified_time": modified,
            "thumbnail_path": slot_thumb_path(slot),
            "summary": summary,
        })
    rows.sort_custom(func(a, b): return a["slot"] < b["slot"])
    return rows


func _peek_summary(slot: int) -> SaveData:
    # Lightweight load just to call .summary(); does NOT populate the cache,
    # since the caller didn't ask for the full object.
    var path := slot_path(slot)
    if not FileAccess.file_exists(path):
        return null
    var res := ResourceLoader.load(path, "Resource", ResourceLoader.CACHE_MODE_IGNORE)
    if res is SaveData:
        return res
    return null


# --- Save -----------------------------------------------------------------

func save_to_slot(slot: int, data: SaveData) -> Error:
    if data == null:
        push_error("SaveManager.save_to_slot(%d): data is null" % slot)
        save_completed.emit(slot, false)
        return ERR_INVALID_PARAMETER
    DirAccess.make_dir_recursive_absolute(SAVE_DIR)
    var final_path := slot_path(slot)
    var tmp_path := final_path + TMP_EXT
    data.version = SaveData.VERSION
    var err := ResourceSaver.save(data, tmp_path)
    if err != OK:
        push_error("SaveManager.save_to_slot(%d): write failed (%d)" % [slot, err])
        save_completed.emit(slot, false)
        return err
    # Atomic rename. DirAccess.rename overwrites the destination on Windows + Unix.
    err = DirAccess.rename_absolute(ProjectSettings.globalize_path(tmp_path),
                                    ProjectSettings.globalize_path(final_path))
    if err != OK:
        # Some filesystems require explicit remove-before-rename.
        DirAccess.remove_absolute(ProjectSettings.globalize_path(final_path))
        err = DirAccess.rename_absolute(ProjectSettings.globalize_path(tmp_path),
                                        ProjectSettings.globalize_path(final_path))
    if err != OK:
        push_error("SaveManager.save_to_slot(%d): rename failed (%d)" % [slot, err])
        save_completed.emit(slot, false)
        return err
    _cache[slot] = data
    clear_dirty()
    save_completed.emit(slot, true)
    return OK


# --- Load -----------------------------------------------------------------

func load_from_slot(slot: int) -> SaveData:
    var path := slot_path(slot)
    if not FileAccess.file_exists(path):
        load_completed.emit(slot, false, null)
        return null
    var res := ResourceLoader.load(path, "Resource", ResourceLoader.CACHE_MODE_IGNORE)
    var data: SaveData = null
    if res is SaveData:
        data = res
        # Run migration if the loaded resource's version is below current.
        if data.version != SaveData.VERSION:
            var as_dict := _resource_to_dict(data)
            data = SaveData.migrate_from(as_dict)
    elif res is Resource:
        # Resource type changed (e.g., class renamed) — round-trip through Dictionary.
        push_warning("SaveManager.load_from_slot(%d): loaded resource is not a SaveData (%s); attempting migration." % [slot, res.get_class()])
        var as_dict := _resource_to_dict(res)
        data = SaveData.migrate_from(as_dict)
    if data == null:
        load_completed.emit(slot, false, null)
        return null
    _cache[slot] = data
    load_completed.emit(slot, true, data)
    return data


func _resource_to_dict(res: Resource) -> Dictionary:
    var d: Dictionary = {}
    for prop in res.get_property_list():
        var name: String = prop.get("name", "")
        # Skip engine-internal properties.
        if name.is_empty() or name.begins_with("_") or name in ["resource_local_to_scene",
                "resource_name", "resource_path", "script"]:
            continue
        d[name] = res.get(name)
    return d


# --- Delete ---------------------------------------------------------------

func delete_slot(slot: int) -> Error:
    var path := slot_path(slot)
    var thumb := slot_thumb_path(slot)
    _cache.erase(slot)
    if FileAccess.file_exists(thumb):
        DirAccess.remove_absolute(ProjectSettings.globalize_path(thumb))
    if FileAccess.file_exists(path):
        return DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
    return ERR_FILE_NOT_FOUND


# --- Quick save shortcut --------------------------------------------------

func quick_save(data: SaveData) -> Error:
    return save_to_slot(0, data)

func quick_load() -> SaveData:
    return load_from_slot(0)
'''


# ---------------------------------------------------------------------------
# autosave.gd emission
# ---------------------------------------------------------------------------

AUTOSAVE_GD = '''## Auto-generated by save-system skill. Attach as a child of any long-lived
## node (e.g. your main scene). Configures a Timer; on each tick, snapshots
## game state IFF SaveManager.is_dirty() is true.
##
## The `_snapshot_state()` callback is project-specific — fill in the body
## marked `# CUSTOMIZE_HERE` with the data your game wants to persist.
extends Node

const AUTOSAVE_SLOT := {slot}
const AUTOSAVE_INTERVAL_SECONDS := {interval}

var _timer: Timer


func _ready() -> void:
    _timer = Timer.new()
    _timer.wait_time = AUTOSAVE_INTERVAL_SECONDS
    _timer.autostart = true
    _timer.one_shot = false
    _timer.timeout.connect(_on_timer)
    add_child(_timer)


func _on_timer() -> void:
    if not SaveManager.is_dirty():
        return  # nothing meaningful changed since last save; skip the I/O
    var data := _snapshot_state()
    if data == null:
        push_warning("Autosave: _snapshot_state() returned null — skipping write.")
        return
    SaveManager.save_to_slot(AUTOSAVE_SLOT, data)


# CUSTOMIZE_HERE -------------------------------------------------------------
# Replace this body with code that builds a SaveData from your current
# gameplay state. The skill cannot infer what your game stores — typical
# things to capture: player position, scene path, inventory, quest flags.
func _snapshot_state() -> SaveData:
    var data := SaveData.new()
    # data.scene_path = get_tree().current_scene.scene_file_path
    # data.player_position = $Player.global_position
    # data.player_health = $Player.health
    return data
'''


# ---------------------------------------------------------------------------
# thumbnail.gd emission
# ---------------------------------------------------------------------------

THUMBNAIL_GD = '''## Auto-generated by save-system skill. Capture a viewport screenshot,
## downsize, and write to the slot's thumbnail path. Call AFTER
## SaveManager.save_to_slot() (so the .tres exists when the slot picker
## scans the saves dir).
extends Node

const THUMB_WIDTH := {w}
const THUMB_HEIGHT := {h}


static func capture(slot: int) -> Error:
    var viewport := Engine.get_main_loop().root if Engine.get_main_loop() else null
    if viewport == null:
        return ERR_UNAVAILABLE
    var img := viewport.get_texture().get_image()
    if img == null:
        return ERR_UNAVAILABLE
    img.resize(THUMB_WIDTH, THUMB_HEIGHT, Image.INTERPOLATE_LANCZOS)
    var path := SaveManager.slot_thumb_path(slot)
    return img.save_png(path)
'''


# ---------------------------------------------------------------------------
# Writers
# ---------------------------------------------------------------------------

def _resolve_output_dir(arg: str) -> Path:
    """Accept both filesystem and res:// paths. Strip res:// to a relative
    path; the agent is expected to be running from the project root."""
    if arg.startswith("res://"):
        return Path(arg[len("res://"):])
    return Path(arg)


def cmd_model(args) -> None:
    out_dir = _resolve_output_dir(args.output)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "save_data.gd"
    path.write_text(_emit_save_data(args.preset), encoding="utf-8")
    print(json.dumps({"ok": True, "wrote": str(path), "preset": args.preset,
                      "fields": len(PRESETS[args.preset]) + 1}, indent=2))


def cmd_manager(args) -> None:
    out_dir = _resolve_output_dir(args.output)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "save_manager.gd"
    path.write_text(MANAGER_GD, encoding="utf-8")
    print(json.dumps({
        "ok": True, "wrote": str(path),
        "next_step": "Register as Autoload named 'SaveManager' "
                     "(Project Settings -> Autoload). Must run before any "
                     "scene that calls save/load.",
    }, indent=2))


def cmd_autosave(args) -> None:
    if args.interval <= 0:
        raise SystemExit("--interval must be > 0")
    out_dir = _resolve_output_dir(args.output)
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "autosave.gd"
    path.write_text(AUTOSAVE_GD.format(slot=args.slot, interval=args.interval),
                    encoding="utf-8")
    print(json.dumps({
        "ok": True, "wrote": str(path), "slot": args.slot, "interval_seconds": args.interval,
        "next_step": "Fill in _snapshot_state() with your project's gameplay state.",
    }, indent=2))


def cmd_thumbnail(args) -> None:
    out_dir = _resolve_output_dir(args.output)
    out_dir.mkdir(parents=True, exist_ok=True)
    if "x" not in args.size:
        raise SystemExit("--size must be WxH, e.g. 320x180")
    w_str, h_str = args.size.split("x", 1)
    w, h = int(w_str), int(h_str)
    path = out_dir / "thumbnail.gd"
    path.write_text(THUMBNAIL_GD.format(w=w, h=h), encoding="utf-8")
    print(json.dumps({"ok": True, "wrote": str(path), "size": [w, h]}, indent=2))


def cmd_all(args) -> None:
    cmd_model(args)
    cmd_manager(args)
    # Defaults for the bundled scaffold:
    class _A: pass
    a = _A(); a.output = args.output; a.slot = args.slot; a.interval = args.interval
    cmd_autosave(a)
    a2 = _A(); a2.output = args.output; a2.size = args.size
    cmd_thumbnail(a2)


def cmd_list(_args) -> None:
    rows = ["Available presets:"]
    for preset, fields in PRESETS.items():
        rows.append(f"  {preset:10s} ({len(fields)} fields)")
        for name, gd_type, default, _c in fields:
            rows.append(f"      {name:22s} {gd_type:18s} default={default}")
        rows.append("")
    print("\n".join(rows))


def main():
    parser = argparse.ArgumentParser(
        description="save-system: Godot 4 save-system scaffold generator")
    sub = parser.add_subparsers(required=True, dest="cmd")

    def _add_output(p):
        p.add_argument("--output", default="res://save/",
                       help="Output directory (default res://save/). Filesystem paths also accepted.")

    p = sub.add_parser("model", help="Emit save_data.gd")
    _add_output(p)
    p.add_argument("--preset", required=True, choices=list(PRESETS))
    p.set_defaults(func=cmd_model)

    p = sub.add_parser("manager", help="Emit save_manager.gd")
    _add_output(p)
    p.set_defaults(func=cmd_manager)

    p = sub.add_parser("autosave", help="Emit autosave.gd")
    _add_output(p)
    p.add_argument("--interval", type=float, default=120.0, help="Seconds between checks (default 120)")
    p.add_argument("--slot", type=int, default=9, help="Slot index for autosave (default 9)")
    p.set_defaults(func=cmd_autosave)

    p = sub.add_parser("thumbnail", help="Emit thumbnail.gd")
    _add_output(p)
    p.add_argument("--size", default="320x180", help="WxH (default 320x180)")
    p.set_defaults(func=cmd_thumbnail)

    p = sub.add_parser("all", help="Emit all four scripts")
    _add_output(p)
    p.add_argument("--preset", required=True, choices=list(PRESETS))
    p.add_argument("--interval", type=float, default=120.0)
    p.add_argument("--slot", type=int, default=9)
    p.add_argument("--size", default="320x180")
    p.set_defaults(func=cmd_all)

    p = sub.add_parser("list", help="List available presets")
    p.set_defaults(func=cmd_list)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
