#!/usr/bin/env python3
"""Game Feel generator — emits a drop-in `GameFeel` autoload (.gd) that gives a
Godot 4 game its "juice": hit-stop, time-punch slow-mo, damage flash, scale-pop
(squash/stretch), screen-shake trigger, and knockback. One autoload, called from
anywhere — the cheapest, highest-impact polish layer.

Good gameplay loops still feel flat without feedback on impact. This is that
feedback layer: `Feel.hit_stop()` on a hit, `Feel.pop(sprite)` on a pickup,
`Feel.flash(sprite, Color.RED)` on damage, `Feel.shake()` on an explosion.

Usage:
  python3 feel_gen.py --profile juicy -o scripts/game_feel.gd
  # then add it as an autoload named "Feel" (Project > Project Settings > Autoload)

Profiles scale the default intensities: subtle / standard / juicy / arcade.
Output: JSON to stdout, the .gd to -o.
"""

import argparse
import json
import sys
from pathlib import Path

# (hit_stop, time_punch_scale, flash_dur, pop_amount, shake_amount, knockback)
PROFILES = {
    "subtle":   dict(hit=0.04, punch=0.6, flash=0.10, pop=1.12, shake=4.0,  kb=120.0),
    "standard": dict(hit=0.08, punch=0.4, flash=0.12, pop=1.25, shake=8.0,  kb=200.0),
    "juicy":    dict(hit=0.12, punch=0.25, flash=0.16, pop=1.40, shake=14.0, kb=320.0),
    "arcade":   dict(hit=0.16, punch=0.15, flash=0.20, pop=1.55, shake=20.0, kb=450.0),
}

TEMPLATE = '''extends Node
## GameFeel — drop-in "juice" autoload. Register as an Autoload named `Feel`
## (Project Settings > Autoload). Call from anywhere: `Feel.hit_stop()`, etc.
## Generated by the game-feel skill (profile: {profile}). Tune the DEFAULT_* consts.

@export var enabled := true

const HIT_STOP_DEFAULT := {hit}
const TIME_PUNCH_SCALE := {punch}
const FLASH_DURATION := {flash}
const POP_AMOUNT := {pop}
const SHAKE_AMOUNT := {shake}
const KNOCKBACK_FORCE := {kb}

## Emitted so a camera (or anything) can react even without a direct reference.
signal shake_requested(amount: float, duration: float)

# --- Hit-stop / freeze-frame -------------------------------------------------
## Briefly freezes time on impact, then restores. Real-time timer so it ticks
## even at time_scale 0. Great on a melee/bullet hit.
func hit_stop(duration: float = HIT_STOP_DEFAULT) -> void:
	if not enabled:
		return
	var prev := Engine.time_scale
	Engine.time_scale = 0.0
	await get_tree().create_timer(duration, true, false, true).timeout
	Engine.time_scale = prev

# --- Time punch (slow-mo burst that eases back to normal) --------------------
func time_punch(scale: float = TIME_PUNCH_SCALE, duration: float = 0.18) -> void:
	if not enabled:
		return
	Engine.time_scale = scale
	var t := create_tween()
	t.set_ignore_time_scale(true)
	t.tween_method(func(s: float): Engine.time_scale = s, scale, 1.0, duration)

# --- Flash (modulate tint, e.g. white on hit / red on damage) ----------------
func flash(node: CanvasItem, color: Color = Color(1, 1, 1), duration: float = FLASH_DURATION) -> void:
	if not enabled or node == null:
		return
	var orig := node.modulate
	node.modulate = color
	var t := create_tween()
	t.tween_property(node, "modulate", orig, duration)

# --- Pop (scale punch — squash/stretch with elastic settle) ------------------
func pop(node: Node, amount: float = POP_AMOUNT, duration: float = 0.20) -> void:
	if not enabled or node == null or not ("scale" in node):
		return
	var base = node.scale
	node.scale = base * amount
	var t := create_tween()
	t.set_trans(Tween.TRANS_ELASTIC).set_ease(Tween.EASE_OUT)
	t.tween_property(node, "scale", base, duration)

# --- Screen shake (delegates to the active Camera2D if it has shake()) -------
func shake(amount: float = SHAKE_AMOUNT, duration: float = 0.25) -> void:
	if not enabled:
		return
	shake_requested.emit(amount, duration)
	var cam := get_viewport().get_camera_2d()
	if cam and cam.has_method("shake"):
		cam.shake(amount, duration)

# --- Knockback (CharacterBody2D velocity or RigidBody2D impulse) --------------
func knockback(body: Node, dir: Vector2, force: float = KNOCKBACK_FORCE) -> void:
	if not enabled or body == null:
		return
	var d := dir.normalized()
	if body is CharacterBody2D:
		body.velocity += d * force
	elif body is RigidBody2D:
		body.apply_central_impulse(d * force)

# --- Combo helper: the classic "got hit" feel in one call --------------------
func impact(node: CanvasItem, dir: Vector2 = Vector2.ZERO) -> void:
	hit_stop()
	flash(node, Color(1, 0.4, 0.4))
	shake()
	if dir != Vector2.ZERO and node.get_parent():
		knockback(node.get_parent(), dir)
'''


def main():
    ap = argparse.ArgumentParser(description="Emit a GameFeel autoload (.gd).")
    ap.add_argument("--profile", choices=list(PROFILES), default="standard")
    ap.add_argument("-o", "--output", required=True)
    args = ap.parse_args()

    p = PROFILES[args.profile]
    gd = TEMPLATE.format(profile=args.profile, **p)
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(gd, encoding="utf-8")
    print(json.dumps({
        "ok": True, "path": str(out), "profile": args.profile,
        "autoload_name": "Feel",
        "methods": ["hit_stop", "time_punch", "flash", "pop", "shake", "knockback", "impact"],
        "next": "Register as Autoload 'Feel'; wire camera-rigs' shake mixin to the shake_requested signal.",
    }))


if __name__ == "__main__":
    main()
