#!/usr/bin/env python3
"""router_index.py — build a compact catalog of every skill in the registry.

Scans the sibling skill directories (../*/SKILL.md relative to this file's
skill) and emits INDEX.md: one row per skill with its title, a one-line purpose
lifted from the SKILL.md, and inferred domain tags. The router preflight reads
that catalog to pick the 1-5 relevant skills for a task WITHOUT loading all of
them into context.

Pure stdlib, deterministic (skills sorted by name), no network, no third-party
deps. Safe to re-run any time a skill is added or reworded:

    python router_index.py                 # writes INDEX.md next to this skill
    python router_index.py --print         # also print the catalog to stdout
    python router_index.py --root DIR      # scan a different skills root
"""
from __future__ import annotations

import argparse
import os
import re
import sys

# Domain taxonomy: tag -> keywords that imply it. Kept small and legible on
# purpose; the router reads the one-line purpose too, so this is a coarse filter,
# not a classifier.
TAXONOMY: dict[str, tuple[str, ...]] = {
    "art/2d": ("pixel", "sprite", "image", "texture", "scene-art", "style", "palette"),
    "art/3d": ("3d", "blender", "daz", "mesh", "rig", "skeleton", "camera"),
    "animation": ("animation", "tween", "vfx", "particle", "shader"),
    "audio": ("audio", "voice", "music", "sound", "tts", "speech"),
    "ui/ux": ("ui", "ux", "hud", "menu", "control node", "theme", "screen", "design", "accessibility"),
    "narrative": ("narrative", "dialogue", "quest", "lore", "story", "gamebook", "interactive fiction", "if-engine", "companion", "npc", "character"),
    "gameplay": ("game feel", "input", "world-layout", "save", "netcode", "multiplayer", "playtest"),
    "engine": ("godot", "unity", "export", "scaffold", "engine"),
    "pipeline": ("pipeline", "manifest", "asset", "preflight", "provider", "reuse"),
    "meta/process": ("council", "decision", "review", "router", "skill", "audit"),
}


def _first_paragraph(body: str) -> str:
    """First non-empty prose paragraph after the H1 (skips blockquotes/code/lists)."""
    lines = body.splitlines()
    # drop the H1 line
    start = 0
    for i, ln in enumerate(lines):
        if ln.startswith("# "):
            start = i + 1
            break
    buf: list[str] = []
    for ln in lines[start:]:
        s = ln.strip()
        if not s:
            if buf:
                break
            continue
        # Real block markers only — require a trailing space on list bullets so a
        # wrapped line that opens with **bold** or *italic* isn't misread as one.
        if s.startswith(("#", ">", "```", "| ", "- ", "* ")) or s in ("|",):
            if buf:
                break
            continue
        buf.append(s)
    text = " ".join(buf)
    text = re.sub(r"\s+", " ", text).strip()
    # de-markdown the common inline noise
    text = text.replace("**", "").replace("`", "")
    return text


def _title(body: str, fallback: str) -> str:
    for ln in body.splitlines():
        if ln.startswith("# "):
            return ln[2:].strip()
    return fallback


def _tags(name: str, title: str, purpose: str) -> list[str]:
    hay = f"{name} {title} {purpose}".lower()
    hits = [tag for tag, kws in TAXONOMY.items() if any(k in hay for k in kws)]
    return hits or ["general"]


def build(root: str) -> list[dict]:
    rows: list[dict] = []
    for name in sorted(os.listdir(root)):
        d = os.path.join(root, name)
        skill_md = os.path.join(d, "SKILL.md")
        if not os.path.isdir(d) or not os.path.isfile(skill_md):
            continue
        with open(skill_md, encoding="utf-8") as fh:
            body = fh.read()
        title = _title(body, name)
        purpose = _first_paragraph(body)
        # trim to a single tight line
        if len(purpose) > 200:
            purpose = purpose[:197].rsplit(" ", 1)[0] + "…"
        rows.append(
            {"name": name, "title": title, "purpose": purpose, "tags": _tags(name, title, purpose)}
        )
    return rows


def render(rows: list[dict]) -> str:
    out = [
        "# Skill Registry Index",
        "",
        f"_{len(rows)} skills. Auto-generated by `skill-router/tools/router_index.py` — do not hand-edit._",
        "",
        "| Skill | Domains | Purpose |",
        "|---|---|---|",
    ]
    for r in rows:
        purpose = r["purpose"].replace("|", "\\|") or "—"
        out.append(f"| `{r['name']}` | {' · '.join(r['tags'])} | {purpose} |")
    out.append("")
    return "\n".join(out)


def main() -> int:
    here = os.path.dirname(os.path.abspath(__file__))
    default_root = os.path.abspath(os.path.join(here, "..", ".."))  # skills/
    ap = argparse.ArgumentParser(description="Build the skill registry index.")
    ap.add_argument("--root", default=default_root, help="skills root to scan")
    ap.add_argument("--out", default=os.path.join(here, "..", "INDEX.md"))
    ap.add_argument("--print", dest="do_print", action="store_true")
    args = ap.parse_args()

    # Windows consoles default to cp1252 and choke on arrows/em-dashes; the
    # file write is always utf-8, but make --print safe too.
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

    rows = build(args.root)
    md = render(rows)
    out_path = os.path.abspath(args.out)
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(md)
    print(f"[router_index] {len(rows)} skills -> {out_path}")
    if args.do_print:
        print()
        print(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
